# Generated by Django 4.2 on 2023-09-15 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_failed_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
